[build-system]
requires = ["setuptools>=64", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "TPOT"
description = "Tree-based Pipeline Optimization Tool"
dynamic = ["version"]
# TODO: this doesn't seem to match code comments
authors = [{ name = "Pedro Ribioro", email = "pedroribeiroh@gmail.com" }]
readme = "README.md"
classifiers=[
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Scientific/Engineering :: Artificial Intelligence"
]
keywords = [
    "pipeline optimization",
    "hyperparameter optimization",
    "data science",
    "machine learning",
    "genetic programming",
    "evolutionary computation"
]
license = "LGPL-3.0-only"
requires-python=">=3.10.0,<3.14.0"

dependencies = [
    "ConfigSpace>=1.1.1",
    "distributed>=2024.4.2",
    "func_timeout>=4.3.5",
    "joblib>=1.1.1",
    "lightgbm>=3.3.3",
    "networkx>=3.0",
    "nose",
    "numpy>=1.26.4",
    "pandas>=2.2.0",
    "scikit-learn>=1.6",
    "scipy>=1.3.1",
    # see [tool.uv.sources] below, upstream using deprecated pkg_resources
    "stopit>=1.1.1",
    "tqdm>=4.36.1",
    "traitlets>=5.8.0",
]

[dependency-groups]
skrebate = ["skrebate>=0.3.4"]
mdr = ["scikit-mdr>=0.4.4"]
sklearnex = ["scikit-learn-intelex>=2023.2.1"]
amltk = ["amltk>=1.12.1"]
testing = [
    "pytest>=6.0",
    "pytest-cov>=2.0",
    "mypy>=0.910",
    "flake8>=3.9",
    "tox>=3.24"
]
cpu = ["xgboost-cpu (>=3.0) ; extra != 'cuda'"]
cuda = ["xgboost (>=3.0) ; extra != 'cpu'"]
nn = ["torch"]
plot = ["matplotlib>=3.6.2"]

[project.urls]
Repository = "https://github.com/EpistasisLab/tpot"
Documentation = "https://epistasislab.github.io/tpot/"

[project.scripts]
tpot = "tpot:main"

[tool.setuptools]
packages = ["tpot"]
zip-safe = true

[tool.setuptools.package-data]
tpot = ["py.typed"]

[tool.flake8]
max-line-length = 120

[tool.setuptools_scm]
# setuptools_scm gets the version from Git tags, e.g git tag v1.1.0
# then python -m build embeds the version into the package

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"
publish-url = "https://upload.pypi.org/tpot/"

[tool.uv.sources]
stopit = { git = "https://github.com/jikamens/stopit" }
